"""add exit-engine state columns to positions

Revision ID: 060db36f1e44
Revises: 815708821b74
Create Date: 2026-08-23 05:02:10.423974

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '060db36f1e44'
down_revision: Union[str, None] = '815708821b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('stop_price', sa.Numeric(precision=38, scale=18), nullable=True))
    op.add_column('positions', sa.Column('take_profit_price', sa.Numeric(precision=38, scale=18), nullable=True))
    op.add_column('positions', sa.Column('trailing_stop_pct', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('positions', sa.Column('highest_price_since_entry', sa.Numeric(precision=38, scale=18), nullable=True))
    op.add_column('positions', sa.Column('max_hold_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'max_hold_seconds')
    op.drop_column('positions', 'highest_price_since_entry')
    op.drop_column('positions', 'trailing_stop_pct')
    op.drop_column('positions', 'take_profit_price')
    op.drop_column('positions', 'stop_price')
    # ### end Alembic commands ###
