"""fix frozen now() server defaults on timestamp columns

Revision ID: 815708821b74
Revises: ce5873669c18
Create Date: 2026-08-23 04:31:59.261903

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '815708821b74'
down_revision: Union[str, None] = 'ce5873669c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('audit_logs', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('copy_trade_signals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('decisions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('fills', 'filled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('market_regimes', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('order_events', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('portfolio_snapshots', 'snapshot_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('position_events', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('risk_events', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('sentiment_events', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('signals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('system_events', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('trader_metrics', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trader_metrics', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'now()'"),
               existing_nullable=False)
    op.alter_column('system_events', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'now()'"),
               existing_nullable=False)
    op.alter_column('signals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'now()'"),
               existing_nullable=False)
    op.alter_column('sentiment_events', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'now()'"),
               existing_nullable=False)
    op.alter_column('risk_events', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'now()'"),
               existing_nullable=False)
    op.alter_column('position_events', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'now()'"),
               existing_nullable=False)
    op.alter_column('portfolio_snapshots', 'snapshot_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'now()'"),
               existing_nullable=False)
    op.alter_column('order_events', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'now()'"),
               existing_nullable=False)
    op.alter_column('market_regimes', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'now()'"),
               existing_nullable=False)
    op.alter_column('fills', 'filled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'now()'"),
               existing_nullable=False)
    op.alter_column('decisions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'now()'"),
               existing_nullable=False)
    op.alter_column('copy_trade_signals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'now()'"),
               existing_nullable=False)
    op.alter_column('audit_logs', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'now()'"),
               existing_nullable=False)
    op.alter_column('alerts', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'now()'"),
               existing_nullable=False)
    # ### end Alembic commands ###
