"""add unique constraint on strategies name+version

Revision ID: ce5873669c18
Revises: ccab0d6964ed
Create Date: 2026-08-23 03:54:53.759490

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ce5873669c18'
down_revision: Union[str, None] = 'ccab0d6964ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_strategy_name_version', 'strategies', ['name', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_strategy_name_version', 'strategies', type_='unique')
    # ### end Alembic commands ###
